"use client";

import { useState } from "react";
import { Bot, CheckCircle2, CircleDollarSign, Database, ShieldCheck, Sparkles } from "lucide-react";

const costCenters = [
  { name: "SEO Analysis", cost: 624, share: 23, detail: "Website scans, keyword and issue analysis" },
  { name: "Content Generation", cost: 1102, share: 41, detail: "Social drafts, blogs, email, and Google Business content" },
  { name: "Social Analytics", cost: 513, share: 19, detail: "Channel interpretation and performance summaries" },
  { name: "Reports", cost: 220, share: 8, detail: "Owner, agency, and customer report generation" },
  { name: "AI Coach", cost: 222, share: 9, detail: "Customer and platform-owner coaching conversations" },
];

export default function AiCostsPage() {
  const [planReady, setPlanReady] = useState(false);
  const totalCost = costCenters.reduce((total, center) => total + center.cost, 0);
  const customers = 312;
  const costPerCustomer = totalCost / customers;

  return <div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-3 text-cyan-300"><CircleDollarSign size={21} /><span className="text-xs font-semibold uppercase tracking-[0.14em]">Platform intelligence</span></div><h1 className="mt-3 text-3xl font-bold text-white">AI cost optimization</h1><p className="mt-2 text-sm text-slate-400">Track AI spend by feature, measure cost per customer, and prepare controlled efficiency improvements.</p></div><div className="flex items-center gap-2 text-sm font-semibold text-cyan-100"><ShieldCheck size={17} />Owner approval required</div></div>
    <section className="border border-cyan-500/30 bg-[#102a43] p-5"><div className="flex items-start gap-3"><Database size={21} className="mt-0.5 shrink-0 text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Usage records required for production</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Each AI usage record should capture the customer or workspace, feature, model, input tokens, output tokens, estimated cost, and timestamp. The platform can then allocate spend by product capability and identify where cost growth diverges from customer value.</p></div></div></section>
    <section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["AI cost · August", `$${totalCost.toLocaleString()}`, "+19% vs. July"], ["Cost per customer", `$${costPerCustomer.toFixed(2)}`, `${customers} active customers`], ["Average revenue per customer", "$59.04", "Healthy gross-margin headroom"], ["Budget status", "$3,000", `$${(3000 - totalCost).toLocaleString()} remaining`]].map(([label, value, detail]) => <article key={label} className="border border-slate-700 bg-slate-900 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-3xl font-bold text-white">{value}</p><p className={`mt-2 text-xs font-semibold ${label === "AI cost · August" ? "text-amber-200" : "text-slate-500"}`}>{detail}</p></article>)}</section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><Bot size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">AI costs · August</h2><p className="mt-1 text-sm text-slate-400">Feature-level allocation of the current platform AI spend.</p></div></div><div className="mt-6 space-y-5">{costCenters.map((center) => <div key={center.name}><div className="flex flex-wrap items-baseline justify-between gap-2"><div><p className="text-sm font-semibold text-white">{center.name}</p><p className="mt-1 text-xs text-slate-500">{center.detail}</p></div><p className="text-sm font-semibold text-cyan-200">${center.cost.toLocaleString()} <span className="text-slate-500">· {center.share}%</span></p></div><div className="mt-2 h-2 bg-slate-800"><div className="h-full bg-cyan-400" style={{ width: `${center.share}%` }} /></div></div>)}</div></div>
      <div className="border border-amber-400/30 bg-amber-400/5 p-5"><div className="flex items-center gap-3"><Sparkles size={20} className="text-amber-300" /><div><h2 className="text-lg font-semibold text-amber-50">AI efficiency opportunity</h2><p className="mt-1 text-sm text-amber-100/70">Content generation drives the largest share of cost.</p></div></div><div className="mt-5 border-l-2 border-amber-300 bg-slate-950/35 p-4"><p className="text-sm font-semibold text-amber-50">Recommendation</p><p className="mt-2 text-sm leading-6 text-amber-100/75">Route short captions, summaries, and classification tasks to lower-cost models. Reserve larger models for long-form content, complex analysis, and high-confidence recommendations.</p></div><button type="button" onClick={() => setPlanReady(true)} className="mt-5 inline-flex w-full items-center justify-center gap-2 bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-300"><Sparkles size={16} />Prepare cost-control plan</button>{planReady && <div className="mt-5 border border-emerald-500/30 bg-emerald-500/10 p-4"><p className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-100"><CheckCircle2 size={17} />Cost-control plan prepared</p><p className="mt-2 text-sm leading-6 text-emerald-100/75">The plan includes model-routing rules, workspace thresholds, and a projected savings checkpoint. No model or customer setting has been changed.</p></div>}</div></section>
    <section className="mt-8 grid gap-4 md:grid-cols-3">{[["Cost per customer", `$${totalCost.toLocaleString()} ÷ ${customers} customers`, `$${costPerCustomer.toFixed(2)} per customer`], ["Revenue coverage", "$59.04 average revenue per customer", "Gross margin remains viable before infrastructure and support costs"], ["Owner action", "Review cost-control plan", "Approve routing changes only after validating quality and customer impact"]].map(([label, formula, result]) => <article key={label} className="border border-slate-700 bg-slate-900 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-cyan-300">{label}</p><p className="mt-3 text-sm font-semibold text-white">{formula}</p><p className="mt-2 text-sm leading-6 text-slate-400">{result}</p></article>)}</section>
  </div>;
}