"use client";

import { useState } from "react";
import { Activity, CheckCircle2, Database, RefreshCw, ServerCog, TriangleAlert } from "lucide-react";

const services = [
  { name: "Application API", status: "Operational", detail: "Average response: 182ms", healthy: true },
  { name: "Supabase", status: "Operational", detail: "Auth and database reachable", healthy: true },
  { name: "Vercel", status: "Operational", detail: "Latest deployment healthy", healthy: true },
  { name: "OpenAI", status: "Configuration required", detail: "No server key configured in this environment", healthy: false },
  { name: "Stripe", status: "Configuration required", detail: "Webhook and live price IDs pending", healthy: false },
  { name: "Google integrations", status: "Attention", detail: "3 connected accounts need token renewal", healthy: false },
];

export default function SystemHealthPage() {
  const [refreshed, setRefreshed] = useState(false);
  return <div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-3 text-cyan-300"><Activity size={21} /><span className="text-xs font-semibold uppercase tracking-[0.14em]">Platform operations</span></div><h1 className="mt-3 text-3xl font-bold text-white">System health</h1><p className="mt-2 text-sm text-slate-400">Application availability, integration readiness, database capacity, and error signals.</p></div><button type="button" onClick={() => setRefreshed(true)} className="inline-flex items-center gap-2 border border-cyan-400 px-4 py-2.5 text-sm font-bold text-cyan-200 hover:bg-cyan-400 hover:text-slate-950"><RefreshCw size={16} />Run health check</button></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => <article key={service.name} className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-white">{service.name}</p><p className="mt-2 text-sm text-slate-400">{service.detail}</p></div>{service.healthy ? <CheckCircle2 size={19} className="text-emerald-300" /> : <TriangleAlert size={19} className="text-amber-300" />}</div><p className={`mt-4 text-xs font-semibold ${service.healthy ? "text-emerald-300" : "text-amber-200"}`}>{service.status}</p></article>)}</section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><Database size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Database capacity</h2><p className="mt-1 text-sm text-slate-400">Operational storage and query health from the platform data layer.</p></div></div><div className="mt-6 space-y-5">{[["Connections", "42%", "Capacity used"], ["Storage", "18%", "Current allocation"], ["Queries / sec", "124", "Average workload"], ["Slow queries", "2", "Need optimization review"]].map(([label, value, detail]) => <div key={label}><div className="flex justify-between text-sm"><span className="text-slate-200">{label}</span><span className="font-semibold text-white">{value}</span></div><p className="mt-1 text-xs text-slate-500">{detail}</p>{label !== "Queries / sec" && label !== "Slow queries" && <div className="mt-2 h-2 bg-slate-800"><div className={`h-full ${label === "Storage" ? "bg-cyan-400" : "bg-amber-400"}`} style={{ width: value }} /></div>}</div>)}</div></div>
      <div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><ServerCog size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Error signals</h2><p className="mt-1 text-sm text-slate-400">Recent exceptions and the operational follow-up they require.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{[["Last 24 hours", "14", "7 are integration retries"], ["Last 7 days", "63", "Most are expired OAuth tokens"], ["Failed scans", "6", "Public sites returned unsupported HTML"], ["Webhook exceptions", "0", "Stripe is not configured yet"]].map(([label, value, detail]) => <article key={label} className="border border-slate-700 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-white">{value}</p><p className="mt-2 text-xs leading-5 text-slate-400">{detail}</p></article>)}</div>{refreshed && <div className="mt-5 border border-emerald-500/30 bg-emerald-500/10 p-4"><p className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-100"><CheckCircle2 size={17} />Health check completed</p><p className="mt-2 text-sm text-emerald-100/75">Core application services are responsive. Three provider credential renewals remain in the owner attention queue.</p></div>}</div></section>
    <section className="mt-8 border border-cyan-400/20 bg-cyan-400/5 p-5"><div className="flex items-start gap-3"><Activity size={20} className="mt-0.5 shrink-0 text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Production monitoring</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">Live health checks should be fed by Vercel observability, Supabase metrics, Stripe webhook outcomes, provider sync jobs, and application error tracking. The owner dashboard should display aggregated operational status only, while detailed logs remain in the secured monitoring tools.</p></div></div></section>
  </div>;
}