"use client";

import { useState } from "react";
import { Activity, Bot, ChartNoAxesCombined, CheckCircle2, Download, FileBarChart, Globe2, RefreshCw, Send, UsersRound } from "lucide-react";

type ReportId = "revenue" | "customers" | "usage" | "marketing" | "health" | "agency";

const reports: { id: ReportId; title: string; description: string; icon: typeof ChartNoAxesCombined; data: { label: string; value: string; detail: string }[]; summary: string }[] = [
  { id: "revenue", title: "Revenue & subscriptions", description: "MRR, ARR, plan mix, payments, churn, and trial conversion.", icon: ChartNoAxesCombined, data: [{ label: "MRR", value: "$18,420", detail: "+12.4% vs. prior period" }, { label: "ARR", value: "$221,040", detail: "Annualized current MRR" }, { label: "Trial conversion", value: "68%", detail: "8 new paid subscriptions" }, { label: "Churn", value: "2.8%", detail: "9 cancellations" }], summary: "Revenue grew through Growth-plan upgrades, while failed payments and cancellation reasons need follow-up before the next billing cycle." },
  { id: "customers", title: "Customer growth & retention", description: "New customers, activation, engagement, and retention risk.", icon: UsersRound, data: [{ label: "New customers", value: "24", detail: "This reporting period" }, { label: "Activation rate", value: "67%", detail: "Completed first business analysis" }, { label: "Active workspaces", value: "86", detail: "Used the app this week" }, { label: "At-risk accounts", value: "9", detail: "No meaningful activity" }], summary: "Customer acquisition is healthy, but seven customers need a targeted reactivation workflow after 30 days without a login." },
  { id: "usage", title: "Product usage & AI cost", description: "Feature adoption, AI actions, requests, and cost-control signals.", icon: Bot, data: [{ label: "AI actions", value: "18,492", detail: "+23% this month" }, { label: "Content drafts", value: "2,431", detail: "Across active workspaces" }, { label: "Website scans", value: "1,204", detail: "91% successful" }, { label: "AI cost change", value: "+19%", detail: "Requires workspace review" }], summary: "AI action adoption is accelerating. Review high-volume workspaces and tighten model routing before costs outpace related revenue." },
  { id: "marketing", title: "Marketing performance", description: "Website, Google, social, content, and recommendation outcomes.", icon: Globe2, data: [{ label: "Organic sessions", value: "12,400", detail: "+8.2% aggregate change" }, { label: "Google impressions", value: "89,400", detail: "+11.4% aggregate change" }, { label: "Social reach", value: "214K", detail: "Across connected channels" }, { label: "Approved actions", value: "1,284", detail: "AI recommendations actioned" }], summary: "Google visibility and social reach lead platform-wide marketing gains; pricing-page conversion remains the most common improvement opportunity." },
  { id: "health", title: "Platform & integration health", description: "Scanner reliability, sync jobs, provider status, and webhook readiness.", icon: Activity, data: [{ label: "Application uptime", value: "99.98%", detail: "Current period" }, { label: "Connected sources", value: "324", detail: "Across customer workspaces" }, { label: "Sync exceptions", value: "3", detail: "Need token renewal" }, { label: "Webhook readiness", value: "Pending", detail: "Stripe configuration required" }], summary: "Core application and scanning services are healthy. Resolve the three integration credential renewals and complete Stripe webhook configuration." },
  { id: "agency", title: "Agency & client export", description: "Client-ready performance summary for agency-managed workspaces.", icon: FileBarChart, data: [{ label: "Agency workspaces", value: "18", detail: "Across 3 agency accounts" }, { label: "Client reports ready", value: "14", detail: "For this period" }, { label: "Growth-score gain", value: "+4.6 pts", detail: "Average active client" }, { label: "Content scheduled", value: "92", detail: "Client content calendar" }], summary: "Agency clients are seeing steady growth-score improvement. Export the summary with business insights, recommended actions, and content calendar status." },
];

export default function ReportsPage() {
  const [selectedId, setSelectedId] = useState<ReportId>("revenue");
  const [period, setPeriod] = useState("This month");
  const [generated, setGenerated] = useState<ReportId | null>(null);
  const [exported, setExported] = useState(false);
  const selected = reports.find((report) => report.id === selectedId) ?? reports[0];
  const Icon = selected.icon;

  function generate() {
    setGenerated(selectedId);
    setExported(false);
  }

  return <div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-3 text-cyan-300"><FileBarChart size={21} /><span className="text-xs font-semibold uppercase tracking-[0.14em]">Platform operations</span></div><h1 className="mt-3 text-3xl font-bold text-white">Reports</h1><p className="mt-2 text-sm text-slate-400">Generate owner, operator, and agency-ready reports from platform and customer signals.</p></div><div className="flex items-center gap-3"><select value={period} onChange={(event) => setPeriod(event.target.value)} className="border border-slate-700 bg-slate-900 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400"><option>This month</option><option>Last month</option><option>Last quarter</option><option>Year to date</option></select><button type="button" onClick={generate} className="inline-flex items-center gap-2 bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-300"><RefreshCw size={16} />Generate report</button></div></div>
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{reports.map((report) => { const ReportIcon = report.icon; const active = report.id === selectedId; return <button type="button" key={report.id} onClick={() => { setSelectedId(report.id); setGenerated(null); setExported(false); }} className={`flex items-start gap-3 border p-4 text-left transition-colors ${active ? "border-cyan-400 bg-cyan-400/10" : "border-slate-700 bg-slate-900 hover:border-slate-500"}`}><ReportIcon size={20} className={active ? "shrink-0 text-cyan-300" : "shrink-0 text-slate-400"} /><span><span className="block text-sm font-semibold text-white">{report.title}</span><span className="mt-1 block text-sm leading-5 text-slate-400">{report.description}</span></span></button>; })}</section>
    <section className="mt-8 border border-slate-700 bg-slate-900 p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center bg-cyan-400/10 text-cyan-300"><Icon size={21} /></div><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-cyan-300">{period}</p><h2 className="mt-1 text-xl font-bold text-white">{selected.title}</h2><p className="mt-2 text-sm text-slate-400">{selected.description}</p></div></div>{generated === selectedId && <span className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-300"><CheckCircle2 size={17} />Report prepared</span>}</div>{generated === selectedId ? <><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{selected.data.map((metric) => <article key={metric.label} className="border border-slate-700 bg-slate-950/40 p-4"><p className="text-xs text-slate-500">{metric.label}</p><p className="mt-2 text-2xl font-bold text-white">{metric.value}</p><p className="mt-2 text-xs leading-5 text-slate-400">{metric.detail}</p></article>)}</div><div className="mt-6 border-l-2 border-cyan-400 bg-slate-950/40 p-4"><p className="text-sm font-semibold text-white">Executive summary</p><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-300">{selected.summary}</p></div><div className="mt-6 flex flex-wrap gap-3 border-t border-slate-800 pt-5"><button type="button" onClick={() => setExported(true)} className="inline-flex items-center gap-2 border border-cyan-400 px-4 py-2.5 text-sm font-bold text-cyan-200 hover:bg-cyan-400 hover:text-slate-950"><Download size={16} />Prepare export</button><button type="button" onClick={() => setExported(true)} className="inline-flex items-center gap-2 bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-300"><Send size={16} />Email report</button>{exported && <span className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-300"><CheckCircle2 size={17} />Export action queued in this demo workspace</span>}</div></> : <div className="mt-6 flex min-h-56 items-center justify-center border border-dashed border-slate-700 bg-slate-950/30 p-8 text-center text-sm leading-6 text-slate-500">Select a period, then generate this report to produce metrics, an executive summary, and an export-ready preview.</div>}</section>
    <section className="mt-8 flex items-start gap-3 border border-cyan-400/20 bg-cyan-400/5 p-4"><ChartNoAxesCombined size={20} className="mt-0.5 shrink-0 text-cyan-300" /><div><p className="text-sm font-semibold text-white">Production reporting architecture</p><p className="mt-1 text-sm leading-6 text-slate-400">These report families will read from Supabase business, usage, subscription, integration, and AI-action records. Scheduled delivery and exports should run server-side, be audited, and use provider data only after secure OAuth or Stripe webhook synchronization.</p></div></section>
  </div>;
}