"use client";

import { useState } from "react";
import { CheckCircle2, Lightbulb, SlidersHorizontal, Sparkles, UsersRound } from "lucide-react";

type Feature = { id: string; name: string; users: number; usage: number; category: string; signal: string };

const features: Feature[] = [
  { id: "dashboard", name: "Dashboard", users: 312, usage: 98, category: "Core", signal: "Primary daily entry point" },
  { id: "social", name: "Social Analytics", users: 281, usage: 90, category: "Analytics", signal: "Most valuable growth insight surface" },
  { id: "seo", name: "SEO Audit", users: 243, usage: 78, category: "Analytics", signal: "Strong use after website connection" },
  { id: "coach", name: "AI Coach", users: 194, usage: 62, category: "AI", signal: "Retention signal when used weekly" },
  { id: "content", name: "Content Generator", users: 151, usage: 48, category: "AI", signal: "Opportunity to connect to automation" },
  { id: "competitors", name: "Competitor Intelligence", users: 72, usage: 23, category: "Research", signal: "Low adoption, needs onboarding review" },
];

export default function ProductOptimizationPage() {
  const [selected, setSelected] = useState<string>("competitors");
  const [experimentReady, setExperimentReady] = useState(false);
  const chosen = features.find((feature) => feature.id === selected) ?? features[0];

  return <div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-3 text-cyan-300"><SlidersHorizontal size={21} /><span className="text-xs font-semibold uppercase tracking-[0.14em]">Platform intelligence</span></div><h1 className="mt-3 text-3xl font-bold text-white">Product optimization</h1><p className="mt-2 text-sm text-slate-400">Understand what customers actually use, then turn adoption gaps into deliberate product and onboarding experiments.</p></div><p className="text-sm text-slate-500">Feature activity · Current period</p></div>
    <section className="border border-cyan-500/30 bg-[#102a43] p-5"><div className="flex items-start gap-3"><Sparkles size={21} className="mt-0.5 shrink-0 text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">AI product readout</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Social Analytics is the highest-value feature after the dashboard. Competitor Intelligence has the largest adoption gap, suggesting that the product may need a simpler first-run path or a clearer connection to a customer&apos;s immediate growth goals.</p></div></div></section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[1.18fr_0.82fr]"><div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><UsersRound size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Feature adoption</h2><p className="mt-1 text-sm text-slate-400">Usage is the percentage of active customers who completed a meaningful action in each feature.</p></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-slate-700 text-xs uppercase tracking-[0.08em] text-slate-500"><tr><th className="pb-3 font-medium">Feature</th><th className="pb-3 font-medium">Users</th><th className="pb-3 font-medium">Usage</th><th className="pb-3 font-medium">Signal</th><th className="pb-3 font-medium"></th></tr></thead><tbody>{features.map((feature) => <tr key={feature.id} className={`border-b border-slate-800 last:border-0 ${selected === feature.id ? "bg-cyan-400/5" : ""}`}><td className="py-4"><p className="font-semibold text-white">{feature.name}</p><p className="mt-1 text-xs text-slate-500">{feature.category}</p></td><td className="py-4 text-slate-200">{feature.users}</td><td className="py-4"><div className="flex items-center gap-3"><span className="w-9 text-slate-200">{feature.usage}%</span><div className="h-1.5 w-24 bg-slate-800"><div className="h-full bg-cyan-400" style={{ width: `${feature.usage}%` }} /></div></div></td><td className="py-4 text-slate-400">{feature.signal}</td><td className="py-4 text-right"><button type="button" onClick={() => { setSelected(feature.id); setExperimentReady(false); }} className="text-xs font-semibold text-cyan-300 hover:text-cyan-200">Analyze</button></td></tr>)}</tbody></table></div></div>
      <aside className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><Lightbulb size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Product opportunity</h2><p className="mt-1 text-sm text-slate-400">Turn a feature signal into an owner-reviewed experiment.</p></div></div><div className="mt-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-cyan-300">Selected feature</p><h3 className="mt-2 text-xl font-bold text-white">{chosen.name}</h3><div className="mt-4 border-l-2 border-cyan-400 bg-slate-950/40 p-4"><p className="text-sm font-semibold text-white">AI recommendation</p><p className="mt-2 text-sm leading-6 text-slate-300">{chosen.id === "competitors" ? "Simplify Competitor Intelligence onboarding. Surface the first competitor suggestion immediately after a customer completes website analysis, then explain the keyword and content gap value." : chosen.id === "social" ? "Keep Social Analytics prominent in the first-analysis experience and use its high adoption to guide customers toward related Content Studio actions." : "Review the first-run path and connect this feature to the most relevant customer growth opportunity."}</p></div><button type="button" onClick={() => setExperimentReady(true)} className="mt-5 inline-flex w-full items-center justify-center gap-2 bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-300"><Sparkles size={16} />Prepare onboarding experiment</button>{experimentReady && <div className="mt-5 border border-emerald-500/30 bg-emerald-500/10 p-4"><p className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-100"><CheckCircle2 size={17} />Experiment brief prepared</p><p className="mt-2 text-sm leading-6 text-emerald-100/75">The proposed audience, onboarding change, success metric, and rollback criteria are ready for owner review. No customer experience has changed.</p></div>}</div></aside></section>
    <section className="mt-8 grid gap-4 md:grid-cols-3">{[["Most valuable", "Social Analytics", "90% usage across 281 customers. Keep this insight surface central to onboarding."], ["Highest opportunity", "Competitor Intelligence", "23% usage across 72 customers. Test a simpler first-run experience."], ["Retention driver", "AI Coach", "62% usage. Encourage a weekly coaching habit for at-risk customers."]].map(([label, title, detail]) => <article key={label} className="border border-slate-700 bg-slate-900 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-cyan-300">{label}</p><h2 className="mt-3 text-lg font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{detail}</p></article>)}</section>
  </div>;
}