import { BadgeDollarSign, CheckCircle2, ExternalLink, Landmark, ShieldCheck, WalletCards } from "lucide-react";

const payoutMetrics = [
  ["Available balance", "$8,421", "Funds eligible for the next Stripe payout"],
  ["Pending balance", "$3,214", "Recent charges still in settlement"],
  ["Next payout", "Aug 25", "Estimated transfer: $8,421"],
  ["Last payout", "$6,832", "Paid Aug 18"],
];

export default function PayoutsPage() {
  return <div className="mx-auto max-w-6xl"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-3 text-cyan-300"><Landmark size={21} /><span className="text-xs font-semibold uppercase tracking-[0.14em]">Platform operations</span></div><h1 className="mt-3 text-3xl font-bold text-white">Payouts & Stripe</h1><p className="mt-2 text-sm text-slate-400">Operational payout visibility for the platform owner. Stripe remains the financial system of record.</p></div><a href="https://dashboard.stripe.com" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 border border-cyan-400 px-4 py-2.5 text-sm font-bold text-cyan-200 hover:bg-cyan-400 hover:text-slate-950"><ExternalLink size={16} />Manage in Stripe</a></div>
    <section className="border border-cyan-500/30 bg-[#102a43] p-6"><div className="flex items-start gap-3"><ShieldCheck size={22} className="mt-0.5 shrink-0 text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Stripe securely handles the money flow</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Customer payments are collected through Stripe Checkout, settled by Stripe, and transferred to the platform&apos;s connected business payout account. MarketGrowthAI never collects, stores, or displays bank-account, routing, or card numbers.</p></div></div><div className="mt-5 grid gap-3 border-t border-cyan-100/15 pt-5 md:grid-cols-3"><FlowStep label="Customer" detail="Subscribes through Stripe Checkout" /><FlowStep label="Stripe" detail="Processes payment and settlement" /><FlowStep label="Connected payout account" detail="Receives Stripe-managed transfers" /></div></section>
    <section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{payoutMetrics.map(([label, value, detail]) => <article key={label} className="border border-slate-700 bg-slate-900 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-3xl font-bold text-white">{value}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></article>)}</section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><WalletCards size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Payout account status</h2><p className="mt-1 text-sm text-slate-400">Only Stripe-provided, non-sensitive payout metadata belongs here.</p></div></div><div className="mt-5 space-y-4">{[
      ["Payout account", "Bank account ending in 4832"],
      ["Connection status", "Connected and payout-enabled"],
      ["Payout schedule", "Weekly, every Monday"],
      ["Identity verification", "Verified by Stripe"],
    ].map(([label, value], index) => <div key={label} className="flex items-center justify-between border-b border-slate-800 pb-4 last:border-0 last:pb-0"><span className="text-sm text-slate-400">{label}</span><span className={`inline-flex items-center gap-1 text-sm font-medium ${index === 1 || index === 3 ? "text-emerald-300" : "text-white"}`}>{(index === 1 || index === 3) && <CheckCircle2 size={15} />}{value}</span></div>)}</div></div>
      <div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><BadgeDollarSign size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Stripe data boundary</h2><p className="mt-1 text-sm text-slate-400">What MarketGrowthAI can safely retain versus what stays only in Stripe.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="border border-emerald-500/25 bg-emerald-500/5 p-4"><p className="text-sm font-semibold text-emerald-100">Store as identifiers</p><ul className="mt-3 space-y-2 text-sm text-emerald-100/75"><li>`stripe_customer_id`</li><li>`stripe_subscription_id`</li><li>`stripe_price_id`</li><li>`stripe_payment_status`</li></ul></div><div className="border border-red-500/25 bg-red-500/5 p-4"><p className="text-sm font-semibold text-red-100">Never store in the app</p><ul className="mt-3 space-y-2 text-sm text-red-100/75"><li>Bank account numbers</li><li>Routing numbers</li><li>Card numbers or CVC</li><li>Stripe secret keys in client code</li></ul></div></div><p className="mt-5 text-sm leading-6 text-slate-400">Use the Stripe Dashboard for payout scheduling, tax forms, account verification, disputes, and detailed transaction history. A production webhook sync should refresh only the operational payout state displayed here.</p></div></section>
  </div>;
}

function FlowStep({ label, detail }: { label: string; detail: string }) { return <div className="border border-cyan-200/15 bg-slate-950/25 p-4"><p className="text-sm font-semibold text-white">{label}</p><p className="mt-1 text-xs leading-5 text-slate-400">{detail}</p></div>; }