"use client";

import { useState } from "react";
import { Bot, CheckCircle2, Lightbulb, SearchCheck, Send, ShieldCheck, Sparkles } from "lucide-react";

type OpportunityId = "cost" | "retention" | "product";

const opportunities: { id: OpportunityId; priority: string; title: string; evidence: string; impact: string; action: string; category: string }[] = [
  { id: "cost", priority: "High priority", category: "AI cost", title: "AI API costs increased 22%", evidence: "Usage rose faster than related subscription revenue, concentrated in a small set of high-volume workspaces.", impact: "Potential savings: $430/month", action: "Investigate model routing and high-volume workspaces" },
  { id: "retention", priority: "Retention", category: "Customer engagement", title: "31 customers have not used AI Coach in 30 days", evidence: "These customers are less likely to generate insights and show lower feature adoption than active cohorts.", impact: "Potential churn risk: High", action: "Prepare a targeted re-engagement campaign" },
  { id: "product", priority: "Product opportunity", category: "Feature adoption", title: "Social Analytics adoption is low", evidence: "67% of customers use Social Analytics, but only 18% use SEO Analytics after onboarding.", impact: "Potential expansion: High", action: "Review onboarding and make Social Analytics a primary path" },
];

export default function OptimizationPage() {
  const [selected, setSelected] = useState<OpportunityId | null>(null);
  const [reviewed, setReviewed] = useState<OpportunityId[]>([]);
  const [campaignReady, setCampaignReady] = useState(false);
  const active = opportunities.find((opportunity) => opportunity.id === selected);

  function markReviewed(id: OpportunityId) {
    setReviewed((current) => current.includes(id) ? current : [...current, id]);
  }

  return <div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-3 text-cyan-300"><Sparkles size={21} /><span className="text-xs font-semibold uppercase tracking-[0.14em]">Platform intelligence</span></div><h1 className="mt-3 text-3xl font-bold text-white">AI Optimization Center</h1><p className="mt-2 text-sm text-slate-400">AI analyzes the SaaS itself to surface cost, retention, product, and adoption opportunities for owner review.</p></div><div className="flex items-center gap-2 text-sm font-semibold text-cyan-100"><ShieldCheck size={17} />Owner approval required</div></div>
    <section className="border border-cyan-500/30 bg-[#102a43] p-5"><div className="flex items-start gap-3"><Bot size={22} className="mt-0.5 shrink-0 text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">How platform optimization works</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">MarketGrowthAI combines product usage, subscription movement, AI cost, integration health, and customer activity to identify optimization opportunities. It can prepare an investigation or campaign, but never sends customer communications or changes product settings without an owner decision.</p></div></div></section>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><div className="space-y-4">{opportunities.map((opportunity) => <article key={opportunity.id} className={`border p-5 ${selected === opportunity.id ? "border-cyan-400 bg-cyan-400/10" : "border-slate-700 bg-slate-900"}`}><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className={`border px-2 py-1 text-xs font-semibold ${opportunity.id === "cost" ? "border-red-400/30 bg-red-400/10 text-red-100" : opportunity.id === "retention" ? "border-amber-400/30 bg-amber-400/10 text-amber-100" : "border-cyan-400/30 bg-cyan-400/10 text-cyan-100"}`}>{opportunity.priority}</span><span className="text-xs text-slate-500">{opportunity.category}</span></div><h2 className="mt-3 text-lg font-semibold text-white">{opportunity.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{opportunity.evidence}</p><p className="mt-3 text-sm font-semibold text-cyan-300">{opportunity.impact}</p></div><button type="button" onClick={() => setSelected(opportunity.id)} className="shrink-0 border border-cyan-400 px-3 py-2 text-xs font-bold text-cyan-200 hover:bg-cyan-400 hover:text-slate-950">{selected === opportunity.id ? "Viewing" : "Investigate"}</button></div>{reviewed.includes(opportunity.id) && <p className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-emerald-300"><CheckCircle2 size={15} />Owner review recorded</p>}</article>)}</div>
      <aside className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><SearchCheck size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Investigation workspace</h2><p className="mt-1 text-sm text-slate-400">Review the selected signal and prepare a controlled follow-up.</p></div></div>{active ? <div className="mt-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-cyan-300">Selected opportunity</p><h3 className="mt-2 text-lg font-semibold text-white">{active.title}</h3><div className="mt-4 border-l-2 border-cyan-400 bg-slate-950/40 p-4"><p className="text-sm font-semibold text-white">Recommended next move</p><p className="mt-2 text-sm leading-6 text-slate-300">{active.action}</p></div>{active.id === "retention" && <button type="button" onClick={() => setCampaignReady(true)} className="mt-5 inline-flex w-full items-center justify-center gap-2 bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-300"><Send size={16} />Prepare re-engagement campaign</button>}{active.id === "cost" && <div className="mt-5 space-y-3 border border-slate-700 bg-slate-950/40 p-4"><p className="text-sm font-semibold text-white">Investigation scope</p><p className="text-sm text-slate-400">Review the top five workspaces by token spend, route low-complexity tasks to lower-cost models, and set per-workspace usage alerts.</p></div>}{active.id === "product" && <div className="mt-5 space-y-3 border border-slate-700 bg-slate-950/40 p-4"><p className="text-sm font-semibold text-white">Product analysis</p><p className="text-sm text-slate-400">Compare completion of Social Analytics and SEO Analytics onboarding, then test a combined first-analysis path for new workspaces.</p></div>}{campaignReady && <div className="mt-5 border border-emerald-500/30 bg-emerald-500/10 p-4"><p className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-100"><CheckCircle2 size={17} />Campaign draft prepared</p><p className="mt-2 text-sm leading-6 text-emerald-100/75">A customer segment and draft message are ready for owner review. No email has been sent.</p></div>}<button type="button" onClick={() => markReviewed(active.id)} className="mt-5 inline-flex w-full items-center justify-center gap-2 border border-cyan-400 px-4 py-2.5 text-sm font-bold text-cyan-200 hover:bg-cyan-400 hover:text-slate-950"><CheckCircle2 size={16} />Mark analysis reviewed</button></div> : <div className="mt-5 flex min-h-72 items-center justify-center border border-dashed border-slate-700 p-6 text-center text-sm leading-6 text-slate-500">Select an optimization signal to see supporting evidence, proposed investigation steps, and safe next actions.</div>}</aside></section>
    <section className="mt-8 grid gap-4 md:grid-cols-3">{[["AI efficiency", "Monitor cost per active workspace, model routing, and high-volume actions."], ["Customer retention", "Surface dormant accounts before they become cancellations."], ["Product opportunity", "Use feature-adoption gaps to prioritize onboarding and roadmap changes."]].map(([title, detail]) => <article key={title} className="border border-slate-700 bg-slate-900 p-5"><Lightbulb size={19} className="text-cyan-300" /><h2 className="mt-3 text-sm font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{detail}</p></article>)}</section>
  </div>;
}