import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, ChartNoAxesCombined, CreditCard, UsersRound } from "lucide-react";

const snapshot = [
  { label: "MRR", value: "$18,420", trend: "+12.4%", direction: "up" },
  { label: "Active customers", value: "312", trend: "+8.2%", direction: "up" },
  { label: "Churn", value: "2.8%", trend: "0.4%", direction: "down" },
  { label: "ARR", value: "$221,040", trend: "Annualized", direction: "flat" },
  { label: "New customers", value: "24", trend: "This month", direction: "flat" },
  { label: "AI usage", value: "18,492", trend: "Actions this month", direction: "flat" },
];

const revenue = [12600, 13400, 14150, 14600, 15300, 16080, 17100, 18420];

export default function AdminDashboard() {
  return <div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-300">Platform operations</p><h1 className="mt-2 text-3xl font-bold text-white">Admin dashboard</h1><p className="mt-2 text-sm text-slate-400">A business-owner view of MarketGrowthAI, from customer growth through system readiness.</p></div><p className="text-sm text-slate-500">Today&apos;s snapshot · Updated just now</p></div>
    <section className="border border-slate-700 bg-slate-900 p-5"><div className="mb-5 flex items-center gap-2"><ChartNoAxesCombined size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Today&apos;s snapshot</h2><p className="mt-1 text-sm text-slate-400">Revenue, customer growth, and product usage at a glance.</p></div></div><div className="grid gap-px overflow-hidden bg-slate-700 sm:grid-cols-2 xl:grid-cols-3">{snapshot.map((metric) => <article key={metric.label} className="bg-slate-900 p-5"><p className="text-sm text-slate-400">{metric.label}</p><p className="mt-2 text-2xl font-bold text-white">{metric.value}</p><p className={`mt-2 inline-flex items-center gap-1 text-xs font-semibold ${metric.direction === "up" || metric.direction === "down" ? "text-emerald-300" : "text-slate-500"}`}>{metric.direction === "up" && <ArrowUpRight size={14} />}{metric.direction === "down" && <ArrowDownRight size={14} />}{metric.trend}</p></article>)}</div></section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[1.18fr_0.82fr]"><div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold text-white">Revenue</h2><p className="mt-1 text-sm text-slate-400">Monthly recurring revenue over the last eight months.</p></div><p className="text-sm font-semibold text-emerald-300">+46.2% since January</p></div><div className="mt-8 flex h-52 items-end gap-3 border-b border-l border-slate-700 px-5 pb-7 pt-4">{revenue.map((amount, index) => <div key={amount} className="flex h-full flex-1 flex-col justify-end gap-2"><div className="group relative bg-cyan-400/80 transition-colors hover:bg-cyan-300" style={{ height: `${(amount / Math.max(...revenue)) * 100}%` }}><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 whitespace-nowrap bg-slate-800 px-2 py-1 text-xs text-white group-hover:block">${amount.toLocaleString()}</span></div><span className="text-center text-xs text-slate-500">{["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"][index]}</span></div>)}</div></div>
      <div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><UsersRound size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Customer growth</h2><p className="mt-1 text-sm text-slate-400">Current customer mix and activity.</p></div></div><div className="mt-6 space-y-4">{[["New customers", "24", "This month"], ["Active customers", "312", "+8.2% this month"], ["Churned customers", "9", "2.8% monthly churn"]].map(([label, value, detail]) => <div key={label} className="flex items-center justify-between border-b border-slate-800 pb-4 last:border-0 last:pb-0"><div><p className="text-sm text-slate-200">{label}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div><p className="text-xl font-bold text-white">{value}</p></div>)}</div></div></section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[0.78fr_1.22fr]"><div className="border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><CreditCard size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Subscriptions</h2><p className="mt-1 text-sm text-slate-400">Active paying customers by plan.</p></div></div><div className="mt-6 space-y-4">{[["Starter", "128", "41%"], ["Growth", "143", "46%"], ["Pro", "41", "13%"]].map(([plan, count, share]) => <div key={plan}><div className="flex justify-between text-sm"><span className="text-slate-200">{plan}</span><span className="text-slate-400">{count} · {share}</span></div><div className="mt-2 h-2 bg-slate-800"><div className="h-full bg-cyan-400" style={{ width: share }} /></div></div>)}</div></div>
      <div className="border border-amber-400/30 bg-amber-400/5 p-5"><div className="flex items-center gap-3"><AlertTriangle size={20} className="text-amber-300" /><div><h2 className="text-lg font-semibold text-amber-50">Attention</h2><p className="mt-1 text-sm text-amber-100/70">Signals that require an owner decision or operational follow-up.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{[
        ["7 customers haven&apos;t logged in for 30 days", "Start a reactivation workflow with their latest opportunity."],
        ["3 failed subscription payments", "Review retry status and customer outreach timing."],
        ["AI API costs increased 19% this week", "Review high-volume workspaces and model usage."],
        ["12 businesses have unused marketing connections", "Prompt connection setup to improve analysis quality."],
      ].map(([title, detail]) => <article key={title} className="border border-amber-300/20 bg-slate-950/35 p-4"><p className="text-sm font-semibold text-amber-50">{title}</p><p className="mt-2 text-sm leading-6 text-amber-100/65">{detail}</p></article>)}</div></div></section>
    <section className="mt-8 border border-slate-700 bg-slate-900 p-5"><div className="flex items-center gap-3"><Activity size={20} className="text-cyan-300" /><div><h2 className="text-lg font-semibold text-white">Platform health</h2><p className="mt-1 text-sm text-slate-400">Operational status of customer-facing capabilities and integrations.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-4">{[["Application", "Operational", "emerald"], ["Website scanner", "Operational", "emerald"], ["Data sync jobs", "3 attention items", "amber"], ["Stripe", "Configuration required", "amber"]].map(([service, status, color]) => <div key={service} className="border border-slate-700 bg-slate-950/40 p-4"><p className="text-sm font-medium text-white">{service}</p><p className={`mt-2 text-xs font-semibold ${color === "emerald" ? "text-emerald-300" : "text-amber-200"}`}>{status}</p></div>)}</div></section>
  </div>;
}